import esbuild from "esbuild";
import process from "process";

// Obsidian community plugin linter 要求不使用 builtin-modules 包
// 直接列出 Node.js 内置模块
const OBSIDIAN_BUILTIN_MODULES = [
	"assert", "child_process", "cluster", "crypto", "dgram", "dns", "domain",
	"events", "fs", "http", "https", "net", "os", "path", "punycode",
	"querystring", "readline", "stream", "string_decoder", "timers", "tls",
	"tty", "url", "util", "v8", "vm", "zlib",
];

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...OBSIDIAN_BUILTIN_MODULES],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}